### ISSUE TITLE
Bug with `multiple=True`

### ISSUE THREAD

**Issue by joneugster** [anntzer/mplcursors#10] opened 2019-01-06 11:21 UTC
Hi, I get some really quirky behavior using the mplcursor.

I tried to capture it in a [video uploaded on Google Drive](https://drive.google.com/open?id=1ylKKAEb8ENwRVxUlEC8ucHVsU9RFRguT).

Could you please have a look and tell me if you need more information?
Thanks.

```
matplotlib.use('Qt5Agg')
...
self.datacursor = mplcursors.cursor(self.ax, multiple=True)
```

pip freeze
<details>

```
certifi==2018.11.29
cycler==0.10.0
Cython==0.29.2
et-xmlfile==1.0.1
jdcal==1.4
kiwisolver==1.0.1
matplotlib==3.0.2
mkl-fft==1.0.6
mkl-random==1.0.1
mplcursors==0.2.1
mpldatacursor==0.6.2
numexpr==2.6.8
numpy==1.15.4
openpyxl==2.5.12
pandas==0.24.0.dev0+1366.g8b4b38fd7
pyparsing==2.3.0
PySide2==5.12.0
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
shiboken2==5.12.0
six==1.12.0
tables==3.4.4
xlrd==1.2.0
```

</details>

**Comment by anntzer** [comment] 2019-01-06 13:44
Thanks for the report.
It's a bit difficult to reproduce this, it looks like it depends on the relative position of the annotation boxes?  (I only saw this happen once after clicking a bunch of times).
This may be related to https://github.com/matplotlib/matplotlib/issues/10875; can you try patching your matplotlib with https://github.com/matplotlib/matplotlib/pull/10776 and check whether it helps? (But even then this may not be enough per https://github.com/matplotlib/matplotlib/issues/10875#issuecomment-375941440.)

**Comment by schneeammer** [comment] 2019-01-06 14:40
I think it reduces to the problem that the click should not be propagated after the first annotation handles it, and the bug #10776 you mentioned above.

**Comment by schneeammer** [comment] 2019-01-06 19:40
Yes this fixes basically all of it. Rewatching the video, 4-7 are also caused by the blit problem and the fixed matplotlib bug. (e.g. in 4, you can see the label appear for one frame)

In my opinion, there are three things left, that are counter-intuitive, but go ahead and close this as fixed :)

- Would be more convenient to only drag one label at a time.
- Selecting a label that lies exactly on a point creates a new label for this point, but the user would like to just move the label. (That happens in 4 in the video, before the label gets invisible)
- Selecting a point that already has a label should not create a second one. This could be solved the following way (although you should do that nicer):

```
diff --git a/lib/mplcursors/_mplcursors.py b/lib/mplcursors/_mplcursors.py
index f7813a6..f78a21e 100644
--- a/lib/mplcursors/_mplcursors.py
+++ b/lib/mplcursors/_mplcursors.py
@@ -300,7 +300,7 @@ class Cursor:
             ha=_MarkedStr("center"), va=_MarkedStr("center"),
             visible=self.visible,
             **self.annotation_kwargs)
-        ann.draggable(use_blit=True)
+        ann.draggable(use_blit=not self._multiple)
         extras = []
         if self._highlight:
             hl = self.add_highlight(*pi)
@@ -485,20 +485,34 @@ class Cursor:
             pi = _pick_info.compute_pick(artist, per_axes_event[artist.axes])
             if pi:
                 pis.append(pi)
+        def _not_contained_in_selection(pi):
+            # Idea: would like to filter out all Selections that
+            # already have a label, so theoretically
+            # `return pi in self._selections` would be nice.
+            for sel in self._selections:
+                if (pi.target == sel.target).all() and pi.artist == sel.artist:
+                    return False
+            return True
+        pis = list(filter(_not_contained_in_selection, pis))
+
         if not pis:
             return

         self.add_selection(min(pis, key=lambda pi: pi.dist))

     def _on_deselect_button_press(self, event):
         if not self._filter_mouse_event(event):
             return
-        for sel in self.selections:
+        for sel in self.selections[::-1]:
             ann = sel.annotation
             if event.canvas is not ann.figure.canvas:
                 continue
             contained, _ = ann.contains(event)
             if contained:
                 self.remove_selection(sel)
+                break
 
     def _on_key_press(self, event):
         if event.key == self.bindings["toggle_enabled"]:
```

**Comment by anntzer** [comment] 2019-01-06 21:20
(1) basically belongs in Matplotlib itself (dragging is entirely implemented by Matplotlib, there is no code in mplcursors for that.
(2) is essentially a Matplotlib issue as well: right now there's no way for mplcursor's event handler to know that the event has already been handled by the drag-handler.
(3) looks reasonable, I slightly adapted your patch in 3fa2e74.

**Comment by anntzer** [comment] 2019-01-06 21:30
Thanks.
As a curiosity, what are you using mplcursors for?

**Closed as completed** 2019-01-06 21:29 UTC

**Comment by schneeammer** [comment] 2019-01-06 21:42
It's a data processing tool we use in our research group at the university to clean the measured meteorological data and prepare it for further research. The cursor helps to select bad data that should be removed.

**Comment by anntzer** [comment] 2019-01-06 22:08
nice, thanks for letting me know.

**Comment by anntzer** [comment] 2020-01-23 10:21
@schneeammer I am considering adding a "list of users" section to the docs; is your data processing tool available somewhere, or has there been any scientific publication based on it?  Either way, please let me know.

**Comment by schneeammer** [comment] 2020-01-23 16:51
Hi,

I am not working on that anymore as I graduated meanwhile. But the program is very much in use, although just internally I’m afraid.
The group is the Grassland sciences Group at ETHZ but Im definitely not the write person to ask as Im not affiliated with them anymore.

Best,
Jon

**Comment by anntzer** [comment] 2020-01-23 17:01
Do you know anyone still there I could ask?  You can send me contact info by email.  If not, no worries :)

**Comment by anntzer** [comment] 2021-04-07 09:48
As it turns out, I figured out a not-too-horrible way to fix "Selecting a label that lies exactly on a point creates a new label for this point, but the user would like to just move the label."  Just in case you're still interested :)
