### ISSUE TITLE
Problem when implementing mplcursors and matplotlib blitting

### ISSUE THREAD

**Issue by jorgesmok** [anntzer/mplcursors#4] opened 2017-12-06 19:47 UTC
Hey, recently I've been learning to use matplotlib's blitting feature to make my GUI's plotting faster. But I notice the mplcursors don't work well when I do it, there are a few issues to mention:

- Some bounding boxes dissapear
- When I press left or right to move along the trace it's slow.
- On matplotlib's animations, after I pause the animation to detail the plot, if I select an artist, the artist dissapears.

I have a callback function for whenever my PyQt4 canvas is drawn and I can see that mplcursors draws the canvas each time I make a selection, I thought mplcursors what based on blitting. 

Is it possible to make mplcursors work with plots based on blitting?

**Comment by anntzer** [comment] 2017-12-07 00:41
Can you provide a specific failing example?

**Comment by jorgesmok** [comment] 2017-12-07 00:56
I got it solved. The problem was that fig.canvas.draw() won't draw any artist whose animated state is 'True'. 

I had integrated your mplcursors as a tool on the matplotlib Navigation Toolbar, so I made sure that everytime I activate your mplcursors, I set the animate state of all my artists that are being animated/blit to 'False'. Now it works nice as usual 👍

I think I can make an example if you want to see the behavior it had.

**Comment by anntzer** [comment] 2017-12-07 01:02
Mostly, do you think it's something that needs to be mentioned in the docs?  If so an example would be good.

**Comment by jorgesmok** [comment] 2017-12-07 01:22
Yes I think it should be mentioned, it's helpful for developers of GUI interactive applications who need fast drawing (animations/blitting) and mplcursors. And I really didn't find any information about it, could have saved me some time of trying to figure it out. I will try to post an example tomorrow.

**Comment by jorgesmok** [comment] 2017-12-07 15:15
Ok, here is a minimal working example using PyQt4 just to add the mplcursor as a checkable action. 

Just pause the animation at any point you want and then activate the mplcursor on the toolbar, then pick a point on the plot, on the first pick everything looks normal, but if you make a second pick or use 'shift+left or right' , the line plot will dissapear. To solve it, just uncomment line 37.

```
import sys
import numpy as np
import matplotlib
matplotlib.use("Qt4Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.animation import FuncAnimation
from PyQt4 import QtGui, QtCore
import mplcursors

class CustomNavigationToolbar(NavigationToolbar):
	
	def __init__(self, canvas, parent=None):
		self.toolitems = (('Home', 'Reset original view', 'home', 'home'),
				('Back', 'Back to  previous view', 'back', 'back'),    
				('Forward', 'Forward to next view', 'forward', 'forward'),
				(None, None, None, None),('Cursor', 'Data Cursor', '', 'cursor'),
				('Pan', 'Pan axes with left mouse, zoom with right', 'move', 'pan'),
				('Zoom', 'Zoom to rectangle', 'zoom_to_rect', 'zoom'),    (None, None, None, None),
				('Subplots', 'Configure subplots', 'subplots', 'configure_subplots'),    
				('Save', 'Save the figure', 'filesave', 'save_figure'),)
		
		super().__init__(canvas, parent)
		
		actions = self.findChildren(QtGui.QAction)
		for a in actions:
			if a.text() == 'Cursor':
				self.cursor_action = a
				a.setCheckable(True)
		
	def cursor(self):
	
		if self.cursor_action.isChecked():
			
			# Uncomment next line to fix problem
			# self.parent.toggle_artists_anim(False)
			self.mpl_cursor = mplcursors.cursor(self.canvas.figure.axes)
			
		else:
			
			self.mpl_cursor.remove()
			
class MyWidget(QtGui.QWidget):
	
	def __init__(self):
		super().__init__()
		
		self.layout = QtGui.QVBoxLayout()
		self.setLayout(self.layout)
		
		self.fig, self.ax = plt.subplots()
		self.canvas = FigureCanvas(self.fig)
		self.canvas.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.toolbar = CustomNavigationToolbar(self.canvas, self)
		self.push_btn = QtGui.QPushButton('Start/Stop')
		self.push_btn.clicked.connect(self.toggle_ani)
		
		self.layout.addWidget(self.toolbar)
		self.layout.addWidget(self.canvas)
		self.layout.addWidget(self.push_btn)
		self.layout.setStretch(1,0)
		
		self.xdata, self.ydata = [], []
		self.ln, = plt.plot([], [], 'ro', animated=True)

		self.ani = FuncAnimation(self.fig, self.update, frames=np.linspace(0, 2*np.pi, 128),
							init_func=self.init, blit=True)
							
		self.ani_running = True
		
	def init(self):
		self.ax.set_xlim(0, 2*np.pi)
		self.ax.set_ylim(-1, 1)
		return self.ln,

	def update(self, frame):
		self.xdata.append(frame)
		self.ydata.append(np.sin(frame))
		self.ln.set_data(self.xdata, self.ydata)
		return self.ln,
		
	def toggle_ani(self):
			
		if self.ani_running:
			self.ani.event_source.stop()
			self.ani_running = False
		else:
			self.ani.event_source.start()
			self.ani_running = True		

	def toggle_artists_anim(self, bool):
		
		self.ln.set_animated(bool)
			
if __name__ == '__main__':
    
	app = QtGui.QApplication(sys.argv)

	w = MyWidget()
	w.resize(800, 600)
	w.show()
	
	sys.exit(app.exec_())
```

If you manually do blitting, you'll have to do the same.

**Comment by anntzer** [comment] 2017-12-07 18:18
A bit busy now, but will keep it on my todo list.

**Comment by anntzer** [comment] 2017-12-08 19:05
I see.  I think that matplotlib's animation framework implicitly assumes that it is entirely in charge of deciding what artists to draw and when, which conflicts with mplcursors trying to add an annotation.  Right now I can't think of a really good way to solve the issue other than adding a note to the docs (but I hope we can come up with some actual fix...).
Let me know how this looks: https://mplcursors.readthedocs.io/en/latest/#animations

**Comment by jorgesmok** [comment] 2018-01-06 22:33
Hi @anntzer, I just updated matplotlib from 2.0.2 to 2.1.1 and I encountered an issue related to this. 

When I use mplcursors I like to set the canvas's cursor to a CrossCursor, it used to work well in matplotlib 2.0.2, but now when I make a second pick, the cursor resets to the default arrow. I tried it with a basic matplotlib example without any animation and it worked fine, so I think it's related to matplotlib's animation/blitting.

It's the same code I posted above, I just added one line `self.canvas.setCursor(QtGui.QCursor(2))`.
Just pause the animation, select the tool 'cursor', make a pick, then make a second pick and you'll see the cursor reseting.

I was reading Qt docs and I found this:

> Some underlying window implementations will reset the cursor if it leaves a widget even if the mouse is grabbed. If you want to have a cursor set for all widgets, even when outside the window, consider QApplication::setOverrideCursor()

 Maybe it's related to this, but I don't want to use QApplication::setOverrideCursor().
```
import sys
import numpy as np
import matplotlib
matplotlib.use("Qt4Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.animation import FuncAnimation
from PyQt4 import QtGui, QtCore
import mplcursors

class CustomNavigationToolbar(NavigationToolbar):
	
	def __init__(self, canvas, parent=None):
		self.toolitems = (('Home', 'Reset original view', 'home', 'home'),
				('Back', 'Back to  previous view', 'back', 'back'),    
				('Forward', 'Forward to next view', 'forward', 'forward'),
				(None, None, None, None),('Cursor', 'Data Cursor', '', 'cursor'),
				('Pan', 'Pan axes with left mouse, zoom with right', 'move', 'pan'),
				('Zoom', 'Zoom to rectangle', 'zoom_to_rect', 'zoom'),    (None, None, None, None),
				('Subplots', 'Configure subplots', 'subplots', 'configure_subplots'),    
				('Save', 'Save the figure', 'filesave', 'save_figure'),)
		
		super().__init__(canvas, parent)
		
		actions = self.findChildren(QtGui.QAction)
		for a in actions:
			if a.text() == 'Cursor':
				self.cursor_action = a
				a.setCheckable(True)
		
	def cursor(self):
	
		if self.cursor_action.isChecked():
			self.canvas.setCursor(QtGui.QCursor(2))
			self.parent.toggle_artists_anim(False)
			self.mpl_cursor = mplcursors.cursor(self.canvas.figure.axes)
			
		else:
			
			self.mpl_cursor.remove()
			
class MyWidget(QtGui.QWidget):
	
	def __init__(self):
		super().__init__()
		
		self.layout = QtGui.QVBoxLayout()
		self.setLayout(self.layout)
		
		self.fig, self.ax = plt.subplots()
		self.canvas = FigureCanvas(self.fig)
		self.canvas.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.toolbar = CustomNavigationToolbar(self.canvas, self)
		self.push_btn = QtGui.QPushButton('Start/Stop')
		self.push_btn.clicked.connect(self.toggle_ani)
		
		self.layout.addWidget(self.toolbar)
		self.layout.addWidget(self.canvas)
		self.layout.addWidget(self.push_btn)
		self.layout.setStretch(1,0)
		
		self.xdata, self.ydata = [], []
		self.ln, = plt.plot([], [], 'ro', animated=True)

		self.ani = FuncAnimation(self.fig, self.update, frames=np.linspace(0, 2*np.pi, 128),
							init_func=self.init, blit=True)
							
		self.ani_running = True
		
	def init(self):
		self.ax.set_xlim(0, 2*np.pi)
		self.ax.set_ylim(-1, 1)
		return self.ln,

	def update(self, frame):
		self.xdata.append(frame)
		self.ydata.append(np.sin(frame))
		self.ln.set_data(self.xdata, self.ydata)
		return self.ln,
		
	def toggle_ani(self):
			
		if self.ani_running:
			self.ani.event_source.stop()
			self.ani_running = False
		else:
			self.ani.event_source.start()
			self.ani_running = True		

	def toggle_artists_anim(self, bool):
		
		self.ln.set_animated(bool)
			
if __name__ == '__main__':
    
	app = QtGui.QApplication(sys.argv)

	w = MyWidget()
	w.resize(800, 600)
	w.show()
	
	sys.exit(app.exec_())
```

**Comment by jorgesmok** [comment] 2018-01-07 02:28
Well, It's even happening when I don't use animations but I implement mplcursors as a tool on the toolbar.

This is a simple example without animation and without toollbar, it works perfectly:
```
import sys
import numpy as np
import matplotlib
matplotlib.use("Qt4Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from PyQt4 import QtGui, QtCore
import mplcursors
			
class MyWidget(QtGui.QWidget):
	
	def __init__(self):
		super().__init__()
		
		self.layout = QtGui.QVBoxLayout()
		self.setLayout(self.layout)
		
		self.fig, self.ax = plt.subplots()
		self.canvas = FigureCanvas(self.fig)
		self.canvas.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.layout.addWidget(self.canvas)
		
		xdata = np.linspace(0, 2*np.pi, 100)
		ydata = np.sin(xdata)
		self.ln, = plt.plot(xdata, ydata)
		
		self.canvas.setCursor(QtGui.QCursor(2))

		self.mpl_cursor = mplcursors.cursor(self.canvas.figure.axes)
			
if __name__ == '__main__':
    
	app = QtGui.QApplication(sys.argv)

	w = MyWidget()
	w.resize(800, 600)
	w.show()
	
	sys.exit(app.exec_())
```

And this is the same example but using a toolbar. When I make a second pick, the cursor resets and every following pick shows a 'loading' circle for less than a second. I could give up on setting a cursor and stay with the default arrow, but it will show that 'loading' circle, which is annoying.

```
import sys
import numpy as np
import matplotlib
matplotlib.use("Qt4Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from PyQt4 import QtGui, QtCore
import mplcursors

class CustomNavigationToolbar(NavigationToolbar):
	
	def __init__(self, canvas, parent=None):
		self.toolitems = (('Home', 'Reset original view', 'home', 'home'),
				('Back', 'Back to  previous view', 'back', 'back'),    
				('Forward', 'Forward to next view', 'forward', 'forward'),
				(None, None, None, None),('Cursor', 'Data Cursor', '', 'cursor'),
				('Pan', 'Pan axes with left mouse, zoom with right', 'move', 'pan'),
				('Zoom', 'Zoom to rectangle', 'zoom_to_rect', 'zoom'),    (None, None, None, None),
				('Subplots', 'Configure subplots', 'subplots', 'configure_subplots'),    
				('Save', 'Save the figure', 'filesave', 'save_figure'),)
		
		super().__init__(canvas, parent)
		
		actions = self.findChildren(QtGui.QAction)
		for a in actions:
			if a.text() == 'Cursor':
				self.cursor_action = a
				a.setCheckable(True)
		
	def cursor(self):
	
		if self.cursor_action.isChecked():
			self.canvas.setCursor(QtGui.QCursor(2))
			self.mpl_cursor = mplcursors.cursor(self.canvas.figure.axes)
			
		else:
			self.canvas.unsetCursor()
			self.mpl_cursor.remove()
			
class MyWidget(QtGui.QWidget):
	
	def __init__(self):
		super().__init__()
		
		self.layout = QtGui.QVBoxLayout()
		self.setLayout(self.layout)
		
		self.fig, self.ax = plt.subplots()
		self.canvas = FigureCanvas(self.fig)
		self.canvas.setFocusPolicy(QtCore.Qt.ClickFocus)
		self.toolbar = CustomNavigationToolbar(self.canvas, self)
		
		self.layout.addWidget(self.toolbar)
		self.layout.addWidget(self.canvas)
		
		xdata = np.linspace(0, 2*np.pi, 100)
		ydata = np.sin(xdata)
		self.ln, = plt.plot(xdata, ydata)
			
if __name__ == '__main__':
    
	app = QtGui.QApplication(sys.argv)

	w = MyWidget()
	w.resize(800, 600)
	w.show()
	
	sys.exit(app.exec_())
```

**Comment by anntzer** [comment] 2018-01-07 02:29
This is due to https://github.com/matplotlib/matplotlib/issues/9546 and is not something I can fix on mplcursors' side.

**Comment by jorgesmok** [comment] 2018-01-07 03:04
Oh I see. I was trying more stuff and I found out that the busy indicator won't appear if I don't add a navigation toolbar. It's a weird behaviour, hope they fix it.

**Comment by anntzer** [comment] 2018-01-23 06:08
That has been reverted in mpl2.2 (soon to be released).

**Comment by anntzer** [comment] 2018-01-25 00:37
I have looked at it again and I believe that the problem is in general unsolvable (because matplotlib's blitting animation can modify artist visibility and animated-flag more or less arbitrarily so I can't even keep track of it).  Updated the docs with a note, and closing as can't-fix (I believe...).

**Closed by anntzer** 2018-01-25 00:37 UTC
