### ISSUE TITLE
Annotation does not delete originally positioned one when moved.

### ISSUE THREAD

**Issue by esba1ley** [anntzer/mplcursors#50] opened 2022-06-14 23:04 UTC
When doing the 4-line example from the website:

```python
import matplotlib.pyplot as plt
import numpy as np
import mplcursors

data = np.outer(range(10), range(1, 5))

fig, ax = plt.subplots()
lines = ax.plot(data)
ax.set_title("Click somewhere on a line.\nRight-click to deselect.\n"
             "Annotations can be dragged.")
fig.tight_layout()

mplcursors.cursor(lines)

plt.show()
```

When I go to re-position a label, it doesn't delete the original one.  See attached video.

Versions:
OS:               MacOS 10.15.7 (Catalina)
python package installer and venv manager:  conda v4.12.0
Python:        v3.9.12
matplotlib:   v3.5.1
mplcursors: v0.5.1

https://user-images.githubusercontent.com/61120205/173703419-2687bcd2-065a-4acf-b618-38587105c588.mp4

**Comment by esba1ley** [comment] 2022-07-25 18:55
It works with the qt backend.

```python
In [1]: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: 
   ...: %matplotlib qt
   ...: 
   ...: import mplcursors
   ...: 
   ...: data = np.outer(range(10), range(1, 5))
   ...: 
   ...: fig, ax = plt.subplots()
   ...: lines = ax.plot(data)
   ...: ax.set_title("Click somewhere on a line.\nRight-click to deselect.\n"
   ...:              "Annotations can be dragged.")
   ...: fig.tight_layout()
   ...: 
   ...: mplcursors.cursor(lines)
   ...: 
   ...: plt.show()
```

You might want to put a caveat in your documentation for mac users to use something other than the "macosx" backend.  "qt" worked for me.

**Comment by petercorke** [comment] 2022-11-29 10:02
I just discovered this package, nice work, but I'm using MacOS and also have this problem.

**Comment by anntzer** [comment] 2023-01-27 22:06
I finally got my hands on a mac to test this with the maces backend, but I still can't reproduce the problem...

**Comment by petercorke** [comment] 2023-01-28 00:07
I just tried this again and that example works well now.  In the interim I have upgraded Matplotlib, now running the latest, but for a long time I was stuck to 3.2 or 3.3.  Thanks for checking this out.

**Comment by anntzer** [comment] 2023-01-28 08:24
Ok, let's close this for now, then.

**Closed by anntzer** 2023-01-28 08:24 UTC
